name: CI - Build e Verificação

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Build dos Containers
        run: docker compose build --no-cache

      - name: Subir Containers
        run: docker compose up -d

      - name: Aguardar inicialização do Banco
        run: sleep 15

      - name: Verificar Status
        run: docker compose ps

      # O comando exato que você usa para testar/mockar
      - name: Rodar Importação de Mock
        run: docker compose exec -T api-fornecedor node /app/data/import-fornecedores.js --import

      - name: Derrubar Containers
        if: always()
        run: docker compose down